// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Calculates a prime number
 */
public class PrimeNumber extends CustomJavaAction<java.lang.String>
{
	private java.lang.Long BitLength;

	public PrimeNumber(IContext context, java.lang.Long BitLength)
	{
		super(context);
		this.BitLength = BitLength;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.Random rnd = new java.security.SecureRandom();
		java.math.BigInteger result = java.math.BigInteger.probablePrime(BitLength.intValue(), rnd);
		return result.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PrimeNumber";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
